### ISSUE TITLE
安装插件之后没有模拟器选项

### ISSUE THREAD

**Issue by witcan** [crazyurus/miniprogram-vscode-extension#18]
![image](https://user-images.githubusercontent.com/48895485/93750171-a4648380-fc2d-11ea-882d-229264b12e1c.png)

**Comment by jiyeme** [comment]
试试看这里
![image](https://user-images.githubusercontent.com/20937135/97441994-534e5a80-1964-11eb-8d7d-fd1e7f1046b2.png)

**Comment by luo12yan** [comment]
> 试试看这里
> ![image](https://user-images.githubusercontent.com/20937135/97441994-534e5a80-1964-11eb-8d7d-fd1e7f1046b2.png)

运行模拟器，报错。

`Error parsing statement => xs.b(i.hoverClass,'none') <= : Unknown Type: CallExpression
    at walk (d:\Green\vscode\plug\crazyurus.miniprogram-vscode-extension-1.3.6\node_modules\wxml-transpiler\build.js:1:6033)
    at walk (d:\Green\vscode\plug\crazyurus.miniprogram-vscode-extension-1.3.6\node_modules\wxml-transpiler\build.js:1:4139)
    at walk (d:\Green\vscode\plug\crazyurus.miniprogram-vscode-extension-1.3.6\node_modules\wxml-transpiler\build.js:1:4079)
    at walk (d:\Green\vscode\plug\crazyurus.miniprogram-vscode-extension-1.3.6\node_modules\wxml-transpiler\build.js:1:3943)
    at walkExp (d:\Green\vscode\plug\crazyurus.miniprogram-vscode-extension-1.3.6\node_modules\wxml-transpiler\build.js:1:6142)
    at parseExp (d:\Green\vscode\plug\crazyurus.miniprogram-vscode-extension-1.3.6\node_modules\wxml-transpiler\build.js:1:6338)
    at parseText (d:\Green\vscode\plug\crazyurus.miniprogram-vscode-extension-1.3.6\node_modules\wxml-transpiler\build.js:1:3639)
    at pushProp (d:\Green\vscode\plug\crazyurus.miniprogram-vscode-extension-1.3.6\node_modules\wxml-transpiler\build.js:1:22554)
    at processAttrs (d:\Green\vscode\plug\crazyurus.miniprogram-vscode-extension-1.3.6\node_modules\wxml-transpiler\build.js:1:21885)
    at Object.start (d:\Green\vscode\plug\crazyurus.miniprogram-vscode-extension-1.3.6\node_modules\wxml-transpiler\build.js:1:17799)
`

**Comment by crazyurus** [comment]
模拟器功能考虑到效果很难对齐微信的实现且很久未维护，在 `1.4.0` 下线了
